name: Xcode - Build and Analyze

on:
  push:
    branches: [ "max" ]
  pull_request:
    branches: [ "max" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ldid
        uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2
      - name: Install trustcache
        run: |
          curl -sSL \
            -o "trustcache" \
          "https://github.com/CRKatri/trustcache/releases/download/v2.0/trustcache_macos_x86_64"
          chmod +x "trustcache"
          cp "trustcache" /usr/local/bin/trustcache
      - name: Build
        run: |
          make ipa
