name: Xcode - Build and Analyze

on:
  push:
    branches: [ "max" ]
  pull_request:
    branches: [ "max" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ldid
        uses: MOZGIII/install-ldid-action@v1
      - name: Build
        run: |
          make ipa
